server:
  port: 8086

spring:
  application:
    name: spring-retrofit

springdoc:
  swagger-ui:
    # 修改Swagger UI路径
    path: /swagger-ui.html
    # 开启Swagger UI界面
    enabled: true
  api-docs:
    # 修改api-docs路径
    path: /v3/api-docs
    # 开启api-docs
    enabled: true
  group-configs:
    - group: 'retrofit'
      packages-to-scan: com.macro.blog.retrofit
  default-flat-param-object: false

remote:
  baseUrl: http://localhost:8080

retrofit:
  # 全局超时配置
  global-timeout:
    # 全局连接超时时间
    connect-timeout-ms: 3000
    # 全局读取超时时间
    read-timeout-ms: 3000
    # 全局写入超时时间
    write-timeout-ms: 35000
    # 全局完整调用超时时间
    call-timeout-ms: 0
  # 全局日志配置
  global-log:
    # 启用日志打印
    enable: true
    # 全局日志打印级别
    log-level: info
    # 全局日志打印策略
    log-strategy: body
  # 全局重试配置
  global-retry:
    # 是否启用全局重试
    enable: true
    # 全局重试间隔时间
    interval-ms: 100
    # 全局最大重试次数
    max-retries: 2
    # 全局重试规则
    retry-rules:
      - response_status_not_2xx
      - occur_exception

