server:
  port: 8088

spring:
  application:
    name: spring-mqtt

springdoc:
  swagger-ui:
    # 修改Swagger UI路径
    path: /swagger-ui.html
    # 开启Swagger UI界面
    enabled: true
  api-docs:
    # 修改api-docs路径
    path: /v3/api-docs
    # 开启api-docs
    enabled: true
  group-configs:
    - group: 'retrofit'
      packages-to-scan: com.macro.blog.mqtt
  default-flat-param-object: false

rabbitmq:
  mqtt:
    url: tcp://192.168.3.101:1883
    username: guest
    password: guest
    defaultTopic: testTopic


