server:
  port: 8080

spring:
  application:
    name: spring-meilisearch

springdoc:
  swagger-ui:
    # 修改Swagger UI路径
    path: /swagger-ui.html
    # 开启Swagger UI界面
    enabled: true
  api-docs:
    # 修改api-docs路径
    path: /v3/api-docs
    # 开启api-docs
    enabled: true
  group-configs:
    - group: 'meilisearch'
      packages-to-scan: com.macro.blog.meilisearch
  default-flat-param-object: false

meilisearch:
  host: http://192.168.3.101:7700
  index: products
